### ISSUE TITLE
Apply agreed project structure

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Notes#1]
The project structure does not adhere to our own guidelines presented at https://docs.starcounter.io/cookbook/project-structure/

What I mean:

- projects should be in `src/` subdirectory of the repo root
- HTML files shoud be in a `views` subdirectory of `wwwroot/<appname>`, not `viewmodels`

This is low prio.

Also, it would be nice to include common batch files: https://starcounter.gitbooks.io/guidelines/content/batch-files.html

**Comment by Joltrix** [comment]
This has been implemented in Notes.
There are some batch files,
the viewmodels folder have been renamed to views,
and the project is inside the src subdirectory. :D

Closing as done :)
